### ISSUE TITLE
Error Unknown request URL when using with React Native

### ISSUE THREAD

**Issue by younes-ammari** [groq/groq-typescript#18]
I'm trying to use Groq in my **React Native** application
I installed the latest **groq-sdk** but i keep getting this error when i used groq-sdk 

`[Error: 404 {"error":{"message":"Unknown request URL: POST /openai/v1/chat/completions/. Please check the URL for typos, or see the docs at https://console.groq.com/docs/","type":"invalid_request_error","code":"unknown_url"}}]`

here is my code:
```
import Groq from 'groq-sdk';
const groq = new Groq({
  apiKey: GROQ_API_KEY,
});
async function main() {
    try {
      const chatCompletion = await groq.chat.completions.create({
        messages: [{ role: 'user', content: 'Explain the importance of low latency LLMs' }],
        model: 'mixtral-8x7b-32768',
      });

      console.log(chatCompletion.choices[0].message.content);
    }

    catch (error) {
      console.error(error);
    }
  }
```

**Comment by gradenr** [comment]
There is an extra `/` in your URL.  I'm not sure how that happened.  What version of the sdk are you using?

**Comment by rattrayalex** [comment]
React Native adds that extra `/` in, and is accordingly not officially supported (as documented in the README). Things should work with a polyfill like this one: https://github.com/acostalima/react-native-polyfill-globals (however, file uploads still won't work).

**Comment by hozen-groq** [comment]
@younes-ammari Were you able to resolve this issue with the above? 👀
