### ISSUE TITLE
Getting ts errors on 0.3.3

### ISSUE THREAD

**Issue by shushui** [groq/groq-typescript#27]
node_modules/groq-sdk/src/core.ts:194:25 - error TS6133: 'opts' is declared but its value is never read.

194   protected authHeaders(opts: FinalRequestOptions): Headers {
                            ~~~~
node_modules/groq-sdk/src/core.ts:221:29 - error TS6133: 'headers' is declared but its value is never read.

221   protected validateHeaders(headers: Headers, customHeaders: Headers) {}
                                ~~~~~~~
node_modules/groq-sdk/src/core.ts:221:47 - error TS6133: 'customHeaders' is declared but its value is never read.

221   protected validateHeaders(headers: Headers, customHeaders: Headers) {}
                                                  ~~~~~~~~~~~~~
node_modules/groq-sdk/src/core.ts:355:34 - error TS6133: 'options' is declared but its value is never read.

355   protected async prepareOptions(options: FinalRequestOptions): Promise<void> {}
                                     ~~~~~~~
node_modules/groq-sdk/src/core.ts:364:5 - error TS6133: 'request' is declared but its value is never read.

364     request: RequestInit,
        ~~~~~~~
node_modules/groq-sdk/src/core.ts:365:5 - error TS6198: All destructured elements are unused.

365     { url, options }: { url: string; options: FinalRequestOptions },
        ~~~~~~~~~~~~~~~~
node_modules/groq-sdk/src/index.ts:147:34 - error TS6133: 'opts' is declared but its value is never read.

147   protected override authHeaders(opts: Core.FinalRequestOptions): Core.Headers {
                                     ~~~~
node_modules/groq-sdk/src/lib/streaming.ts:190:18 - error TS7006: Parameter 'ctrl' implicitly has an 'any' type.

190       async pull(ctrl) {
                     ~~~~

Found 8 error(s).

**Comment by hozen-groq** [comment]
@shushui Hi there! 👋 Apologies for such a late response here - I hope you're able to use our latest SDK with no hiccups. Please let us know if you run into anything. The best way to reach us for a quick response is the "Chat with us" live chat feature on console.groq.com.
