### ISSUE TITLE
Where do we set a Api key and a costum baseurl? 

### ISSUE THREAD

**Issue by onigetoc** [groq/groq-typescript#46]
Where i how do we set a Api key and a custom baseurl to make it compatible wirh Openai API?

**Comment by gradenr** [comment]
If you want to use the OpenAI SDK with groq, set your base URL to `https://api.groq.com/openai/v1`

```
export OPENAI_BASE_URL="https://api.groq.com/openai/v1"
export OPENAI_API_KEY-"gsk_..."
python example.py
```

**Comment by rattrayalex** [comment]
You can also use do the same with this SDK:

```bash
export GROQ_BASE_URL="https://my-compatible-ai-api.com/foo/"
export GROQ_API_KEY="..."
node example.ts
```
or, directly in code:
```ts
const client = new Groq({ 
  apiKey: '…', 
  baseURL: 'https://my-compatible-ai-api.com/foo/',
})
```

**Comment by onigetoc** [comment]
Hi, OpenAI have something like that?
I use it with nodejs and in the browser.
```
openaiConfiguration.baseOptions.headers = {
  Authorization: "Bearer " + openaiKey,
};
```

Do we need something like that for Groq?

**Comment by hozen-groq** [comment]
@onigetoc Hi there and apologies for such a late response here! I hope you were able to figure this out and, if not, we have a section in our docs that has more detail for this: https://console.groq.com/docs/openai. Happy building!
