### ISSUE TITLE
Unable to access `CompletionCreateParams` from `Groq.Chat.CompletionCreateParams`

### ISSUE THREAD

**Issue by bracesproul** [groq/groq-typescript#6]
When trying to access `Groq.Chat.CompletionCreateParams` or `Groq.Chat.Completions.CompletionCreateParams` (which my VSCode auto complete suggests as valid imports) I get the following error:

```
Namespace '"/Users/bracesproul/code/lang-chain-ai/langchainjs/node_modules/groq-sdk/resources/chat/chat".Chat' has no exported member 'CompletionCreateParams'.ts(2694)
```

[TSConfig](https://github.com/langchain-ai/langchainjs/blob/main/libs/langchain-community/tsconfig.json)

`groq-sdk` version: `0.2.1` (latest)

Is there a different recommended way to access this interface?

**Comment by hozen-groq** [comment]
Hi, Brace! Thanks for reaching out. The team is currently looking into this and I'll try to post an update soon. 🤞

**Comment by bracesproul** [comment]
> Hi, Brace! Thanks for reaching out. Could you please try again with `groq-sdk` version 0.3.0?

still getting the same error :(

**Comment by dackerman** [comment]
Hi @bracesproul - if you're looking to implement an interface, then `Groq.Chat.CompletionCreateParams` is a namespace, not an interface. Maybe you mean `Groq.Chat.CompletionCreateParams.Message` (which is an interface)?

something like:

```
class MyParams implements Groq.Chat.CompletionCreateParams.Message {
  get role() {
    return 'somerole';
  }
  get content() {
    return 'somecontent';
  }
}
```

If you want just the type of the whole params object, that would be `ChatCompletionCreateParams` which you can import like so:

    import { ChatCompletionCreateParams } from 'groq-sdk/resources/chat/completions';
    
    function makeParams(): ChatCompletionCreateParams {...}
 
It might help to look at [completions.ts](https://github.com/groq/groq-typescript/blob/6c7d67490e5f40e30add223d5661b66d9240a391/src/resources/chat/completions.ts#L264) to see how these things are defined more clearly. Does that help?

**Comment by bracesproul** [comment]
> Hi @bracesproul - if you're looking to implement an interface, then `Groq.Chat.CompletionCreateParams` is a namespace, not an interface. Maybe you mean `Groq.Chat.CompletionCreateParams.Message` (which is an interface)?
> 
> something like:
> 
> ```
> class MyParams implements Groq.Chat.CompletionCreateParams.Message {
>   get role() {
>     return 'somerole';
>   }
>   get content() {
>     return 'somecontent';
>   }
> }
> ```
> 
> If you want just the type of the whole params object, that would be `ChatCompletionCreateParams` which you can import like so:
> 
> ```
> import { ChatCompletionCreateParams } from 'groq-sdk/resources/chat/completions';
> 
> function makeParams(): ChatCompletionCreateParams {...}
> ```
> 
> It might help to look at [completions.ts](https://github.com/groq/groq-typescript/blob/6c7d67490e5f40e30add223d5661b66d9240a391/src/resources/chat/completions.ts#L264) to see how these things are defined more clearly. Does that help?

Importing from the path you listed fixed it, I appreciate it!

**Comment by oeyoews** [comment]
I'm troubled by the same problem. I think this can be temporarily updated to the readme.
